version: '3.8'

services:
  app:
    image: 'exelances/fitnesapi:latest'
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=qrmenu
      - POSTGRES_PASSWORD=lOJ5RddOsSSVdX86oXFXkQEgv0DSZO5jlk6hFotlMSYRcaKOTCWqHg57CB0kbZwk
      - SPRING_DATASOURCE_URL=jdbc:postgresql://2.59.117.162:5432/postgres
      - SPRING_DATASOURCE_USERNAME=qrmenu
      - SPRING_DATASOURCE_PASSWORD=lOJ5RddOsSSVdX86oXFXkQEgv0DSZO5jlk6hFotlMSYRcaKOTCWqHg57CB0kbZwk
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '5050:5050'
        